// ==========================================
// Tolani Commerce College - Student Database
// B.Com. Sem - I (2024-25) NEP Roster
// ==========================================

const TOLANI_STUDENTS = [
    {
        "username": "1",
        "password": "2024001483",
        "spdid": "2024001483",
        "rollNo": "1",
        "name": "AADITYA HIMMATLAL BALDANIYA",
        "gender": "Male",
        "category": "SEBC",
        "email": "adityabaldaniya16@gmail.com",
        "phone": "+91 90540 14550",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "2",
        "password": "2024001507",
        "spdid": "2024001507",
        "rollNo": "2",
        "name": "ABHISHEK DINESHKUMAR PANDEY",
        "gender": "Male",
        "category": "General",
        "email": "abhishekdpandey6791@gmail.com",
        "phone": "+91 93283 07540",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "3",
        "password": "2024001479",
        "spdid": "2024001479",
        "rollNo": "3",
        "name": "ADITYA CHAUDHARY .",
        "gender": "Male",
        "category": "General",
        "email": "aditya30chaudhary2005@gmail.com",
        "phone": "+91 88103 80556",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "C" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "4",
        "password": "2024001480",
        "spdid": "2024001480",
        "rollNo": "4",
        "name": "ANUJ BODHRAJ BANMOTRA",
        "gender": "Male",
        "category": "General",
        "email": "anujbanmotra062@gmail.com",
        "phone": "+91 82389 27644",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A+" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "5",
        "password": "2024001481",
        "spdid": "2024001481",
        "rollNo": "5",
        "name": "ARVIND SHARMA .",
        "gender": "Male",
        "category": "General",
        "email": "arvindshrma004@gmail.com",
        "phone": "+91 78638 96056",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "6",
        "password": "2024001513",
        "spdid": "2024001513",
        "rollNo": "6",
        "name": "BANSARI GAUTAMBHAI RAVAL",
        "gender": "Female",
        "category": "General",
        "email": "bansrir33@gmail.com",
        "phone": "+91 63520 09595",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "7",
        "password": "2024001512",
        "spdid": "2024001512",
        "rollNo": "7",
        "name": "BHARTI SUNILSINGH RANA",
        "gender": "Female",
        "category": "General",
        "email": "bharatirana2005@gmail.com",
        "phone": "+91 97144 06713",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "8",
        "password": "2024001487",
        "spdid": "2024001487",
        "rollNo": "8",
        "name": "DEBABRATA SWAIN .",
        "gender": "Male",
        "category": "General",
        "email": "debabrata06swain@gmail.com",
        "phone": "+91 99798 84167",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "C" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "C" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "9",
        "password": "2024001529",
        "spdid": "2024001529",
        "rollNo": "9",
        "name": "DEEP JITENDRABHAI VAGHAMSHI",
        "gender": "Male",
        "category": "SEBC",
        "email": "deepvaghamshi07@gmail.com",
        "phone": "+91 63511 02064",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "10",
        "password": "2024001504",
        "spdid": "2024001504",
        "rollNo": "10",
        "name": "DEVANSH BHARATBHAI KOTECHA",
        "gender": "Male",
        "category": "General",
        "email": "devanshkotecha251@gmail.com",
        "phone": "+91 92651 85421",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B+" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B+" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "12",
        "password": "2024001517",
        "spdid": "2024001517",
        "rollNo": "12",
        "name": "HASMITA MAHESHBHAI SHEGALIYA",
        "gender": "Female",
        "category": "General",
        "email": "ranishegaliya@gmail.com",
        "phone": "+91 63527 88873",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A+" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "13",
        "password": "2024001494",
        "spdid": "2024001494",
        "rollNo": "13",
        "name": "HITANSHI SANTOSH MAHARANA",
        "gender": "Female",
        "category": "General",
        "email": "maharanahitanshi971@gmail.com",
        "phone": "+91 90547 31190",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "C" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "14",
        "password": "2024001496",
        "spdid": "2024001496",
        "rollNo": "14",
        "name": "ISHA BHAVESH SHARMA",
        "gender": "Female",
        "category": "General",
        "email": "dadhichisha85@gmail.com",
        "phone": "+91 94266 82723",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A+" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "15",
        "password": "2024001499",
        "spdid": "2024001499",
        "rollNo": "15",
        "name": "JAYDEEP HIRENKUMAR JANI",
        "gender": "Male",
        "category": "General",
        "email": "janijaydeep510@gmail.com",
        "phone": "+91 74900 60825",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "C" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "C" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "16",
        "password": "2024001490",
        "spdid": "2024001490",
        "rollNo": "16",
        "name": "JENISH DINESHGAR GOSAI",
        "gender": "Male",
        "category": "SEBC",
        "email": "gosaijenish155@gmail.com",
        "phone": "+91 98254 22034",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B+" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "17",
        "password": "2024001519",
        "spdid": "2024001519",
        "rollNo": "17",
        "name": "JYOTI SATYENDRA SINGH",
        "gender": "Female",
        "category": "General",
        "email": "jyotisingh08012007@gmail.com",
        "phone": "+91 63544 65196",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "18",
        "password": "2024001531",
        "spdid": "2024001531",
        "rollNo": "18",
        "name": "KHUSHI KAMLESH VAGHELA",
        "gender": "Female",
        "category": "General",
        "email": "Sahilvaghela06735@gmail.com",
        "phone": "+91 63536 02116",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "19",
        "password": "2024001482",
        "spdid": "2024001482",
        "rollNo": "19",
        "name": "KRISHNA HARESH BAHERWANI",
        "gender": "Male",
        "category": "General",
        "email": "k7525496@gmail.com",
        "phone": "+91 99136 70886",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B+" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "20",
        "password": "2024001495",
        "spdid": "2024001495",
        "rollNo": "20",
        "name": "LALJIBHAI PACHANBHAI HUMBAL",
        "gender": "Male",
        "category": "SEBC",
        "email": "pachanhumbal1974@gmail.com",
        "phone": "+91 63544 07108",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "C" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "C" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "C" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "21",
        "password": "2024001525",
        "spdid": "2024001525",
        "rollNo": "21",
        "name": "LAXMI RAMMURATSINGH THAKUR",
        "gender": "Female",
        "category": "General",
        "email": "laxmithakur459@gmail.com",
        "phone": "+91 96646 09773",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B+" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "22",
        "password": "2024001497",
        "spdid": "2024001497",
        "rollNo": "22",
        "name": "MAHIPALSINH HOSHIYARSINH JADEJA",
        "gender": "Male",
        "category": "General",
        "email": "jmahipalsinh19@gmail.com",
        "phone": "+91 79843 37904",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "A+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "23",
        "password": "2024001502",
        "spdid": "2024001502",
        "rollNo": "23",
        "name": "MANN MAYUR KANSARA",
        "gender": "Male",
        "category": "EWS",
        "email": "mannkansara100@gmail.com",
        "phone": "+91 90166 59199",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "24",
        "password": "2024001509",
        "spdid": "2024001509",
        "rollNo": "24",
        "name": "MIHIN HASSAN PRADHAN",
        "gender": "Male",
        "category": "General",
        "email": "pradhanmihin19@gmail.com",
        "phone": "+91 63554 65031",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B+" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "25",
        "password": "2024001518",
        "spdid": "2024001518",
        "rollNo": "25",
        "name": "MOHAMMAD SAHIL NASIM SHEIKH",
        "gender": "Male",
        "category": "General",
        "email": "sheikhsahiln98@gmail.com",
        "phone": "+91 91577 88558",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "26",
        "password": "2024001526",
        "spdid": "2024001526",
        "rollNo": "26",
        "name": "MUSKAN GORDHAN THAKUR",
        "gender": "Female",
        "category": "General",
        "email": "thakurgordhan@gmail.com",
        "phone": "+91 99255 24433",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "27",
        "password": "2024001505",
        "spdid": "2024001505",
        "rollNo": "27",
        "name": "NAITIK PARMAR .",
        "gender": "Male",
        "category": "SEBC",
        "email": "nparmar9792@gmail.com",
        "phone": "+91 90995 10094",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "28",
        "password": "2024001535",
        "spdid": "2024001535",
        "rollNo": "28",
        "name": "NANDANI MUKESH GOSWAMI",
        "gender": "Female",
        "category": "General",
        "email": "ajaygoswami116@gmail.com",
        "phone": "+91 80007 30356",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A+" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "30",
        "password": "2024001528",
        "spdid": "2024001528",
        "rollNo": "30",
        "name": "PAYAL PRAKASH UJJAWAL",
        "gender": "Female",
        "category": "SC",
        "email": "payalujjawal5@gmail.com",
        "phone": "+91 92651 29200",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "31",
        "password": "2024001493",
        "spdid": "2024001493",
        "rollNo": "31",
        "name": "POOJA KESHAVJI HADIYA",
        "gender": "Female",
        "category": "SEBC",
        "email": "sorathiyapooja430@gmail.com",
        "phone": "+91 97270 71173",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B+" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "32",
        "password": "2024001511",
        "spdid": "2024001511",
        "rollNo": "32",
        "name": "PRANAV NARESH RAMCHANDANI",
        "gender": "Male",
        "category": "General",
        "email": "pranavn473@gmail.com",
        "phone": "+91 93913 41804",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "33",
        "password": "2024001532",
        "spdid": "2024001532",
        "rollNo": "33",
        "name": "PRIYA MANOJ YADAV",
        "gender": "Female",
        "category": "General",
        "email": "myadav7728@gmail.com",
        "phone": "+91 79907 80758",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "34",
        "password": "2024001521",
        "spdid": "2024001521",
        "rollNo": "34",
        "name": "PRIYANK YOGESH SORATHIYA",
        "gender": "Male",
        "category": "SEBC",
        "email": "priyanksorthiya5@gmail.com",
        "phone": "+91 98989 05078",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "35",
        "password": "2024001488",
        "spdid": "2024001488",
        "rollNo": "35",
        "name": "ROHINI PHOOLNAYAN DUBEY",
        "gender": "Female",
        "category": "General",
        "email": "dubeyrohini324@gmail.com",
        "phone": "+91 90233 87274",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "36",
        "password": "2024001484",
        "spdid": "2024001484",
        "rollNo": "36",
        "name": "RONAK HEMANT BHEJWAL",
        "gender": "Male",
        "category": "General",
        "email": "ronakbhejwal@gmail.com",
        "phone": "+91 97276 16190",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "C" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "37",
        "password": "2024001538",
        "spdid": "2024001538",
        "rollNo": "37",
        "name": "SAHIL UMAJI PRASAD",
        "gender": "Male",
        "category": "General",
        "email": "kumarsahil5949@gmail.com",
        "phone": "+91 99981 72347",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "38",
        "password": "2024001491",
        "spdid": "2024001491",
        "rollNo": "38",
        "name": "SHIVAMRAJ KANIYA PRASAD GUPTA",
        "gender": "Male",
        "category": "General",
        "email": "kanhaiyakgupta0555@gmail.com",
        "phone": "+91 87589 48850",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "39",
        "password": "2024001533",
        "spdid": "2024001533",
        "rollNo": "39",
        "name": "SUMAN PRAKASH YADAV",
        "gender": "Female",
        "category": "General",
        "email": "vk5179038@gmail.com",
        "phone": "+91 81284 06416",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "40",
        "password": "2024001527",
        "spdid": "2024001527",
        "rollNo": "40",
        "name": "TUSHAR MANOJ SHARMA",
        "gender": "Male",
        "category": "General",
        "email": "tusharsharma.sharma27@gmail.com",
        "phone": "+91 95589 35582",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "C" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "41",
        "password": "2024001515",
        "spdid": "2024001515",
        "rollNo": "41",
        "name": "YASHVI MAGANBHAI SANJOT",
        "gender": "Female",
        "category": "SC",
        "email": "sanjotbhartibhartisanjot@gmail.com",
        "phone": "+91 63523 21014",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B+" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "42",
        "password": "2024001523",
        "spdid": "2024001523",
        "rollNo": "42",
        "name": "ASHA BHAWARLAL SUTHAR",
        "gender": "Female",
        "category": "General",
        "email": "bhawarsuthar959@gmail.com",
        "phone": "+91 70431 65018",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "43",
        "password": "2024001514",
        "spdid": "2024001514",
        "rollNo": "43",
        "name": "PRAGATI KISHOR ROSHIYA",
        "gender": "Female",
        "category": "SC",
        "email": "aarumaheshwari26@gmail.com",
        "phone": "+91 95860 95738",
        "subject": "Stat",
        "class": "B.Com. Sem-I - Stat",
        "role": "student",
        "department": "B.Com. (NEP) - Statistics",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A+" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Statistics", "credits": 4, "code": "BC-Stat-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "44",
        "password": "2024001530",
        "spdid": "2024001530",
        "rollNo": "44",
        "name": "ADITYA PREMDAS VAGHELA",
        "gender": "Male",
        "category": "SC",
        "email": "adityavaghela68@gmail.com",
        "phone": "+91 98799 64898",
        "subject": "BA",
        "class": "B.Com. Sem-I - BA",
        "role": "student",
        "department": "B.Com. (NEP) - Business Administration",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "C" },
            { "subject": "Business Administration", "credits": 4, "code": "BC-BA-104", "grade": "C" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "45",
        "password": "2024001540",
        "spdid": "2024001540",
        "rollNo": "45",
        "name": "HIREN RANABHAI VADA",
        "gender": "Male",
        "category": "SEBC",
        "email": "hirenahir706@gmail.com",
        "phone": "+91 63529 55747",
        "subject": "BM",
        "class": "B.Com. Sem-I - BM",
        "role": "student",
        "department": "B.Com. (NEP) - Business Management",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "B" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "B+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "B" },
            { "subject": "Business Management", "credits": 4, "code": "BC-BM-104", "grade": "B" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    },
    {
        "username": "47",
        "password": "2024001524",
        "spdid": "2024001524",
        "rollNo": "47",
        "name": "VINAY DINESH THAKAR",
        "gender": "Male",
        "category": "General",
        "email": "vinaythakar7070@gmail.com",
        "phone": "+91 95374 25771",
        "subject": "CS",
        "class": "B.Com. Sem-I - CS",
        "role": "student",
        "department": "B.Com. (NEP) - Computer Science",
        "feeStatus": { "status": "unpaid", "due": 6200, "total": 6200, "paid": 0 },
        "grades": [
            { "subject": "Financial Accounting", "credits": 4, "code": "BC-101", "grade": "A" },
            { "subject": "Business Organisation", "credits": 4, "code": "BC-102", "grade": "A+" },
            { "subject": "Microeconomics", "credits": 3, "code": "BC-103", "grade": "A" },
            { "subject": "Computer Science", "credits": 4, "code": "BC-CS-104", "grade": "A" }
        ],
        "attendance": { "2026-07-09": "present", "2026-07-06": "present", "2026-07-10": "present", "2026-07-08": "present" }
    }
];
